server.port=${PORT:8080}
spring.application.name=biyahero-api

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

logging.level.root=INFO
logging.level.com.biyahero=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

spring.mvc.pathmatch.use-suffix-pattern=false
